/*
 * This file is part of XUI.
 * Licensed under LGPL 3.0.
 */
package net.xmx.xui.core.components.markdown;

import net.xmx.xui.core.Layout;
import net.xmx.xui.core.components.UIPanel;
import net.xmx.xui.core.components.UIWrappedText;
import net.xmx.xui.core.font.Font;
import net.xmx.xui.core.style.CornerRadii;
import net.xmx.xui.core.style.ThemeProperties;
import net.xmx.xui.core.text.TextComponent;

import java.util.List;

/**
 * Represents a Code Block in Markdown (```).
 * Renders text with syntax highlighting inside a dark box.
 *
 * @author xI-Mx-Ix
 */
public class MarkdownCodeBlock extends UIPanel {

    private final float renderHeight;

    /**
     * Constructs a code block component.
     *
     * @param lines        The lines of code.
     * @param contentWidth The available width.
     * @param font         The font to use for the code text.
     */
    public MarkdownCodeBlock(List<String> lines, float contentWidth, Font font) {
        StringBuilder sb = new StringBuilder();
        for (String s : lines) sb.append(s).append("\n");

        String code = sb.toString();
        // Retrieve the font height from the provided font instance
        float fontHeight = font.getLineHeight();

        // Apply syntax highlighting to the raw code string, returning a styled TextComponent tree
        TextComponent coloredCode = MarkdownUtils.highlightCode(code);

        // IMPORTANT: Recursively apply the code font to all highlight segments
        MarkdownUtils.applyFontRecursive(coloredCode, font);

        // Create wrapping text widget to handle line breaks
        UIWrappedText content = MarkdownUtils.createWrappingText(coloredCode, 0, contentWidth);

        float padding = 6;

        // Calculate the visual height based on the number of lines provided.
        // This ensures the height is correct immediately, without relying on the internal layout state of the text widget.
        int lineCount = lines.isEmpty() ? 1 : lines.size();
        float contentVisualHeight = lineCount * fontHeight;

        // Total height includes the content height plus top and bottom padding
        float totalHeight = contentVisualHeight + (padding * 2);

        this.setWidth(Layout.pixel(contentWidth));
        this.setHeight(Layout.pixel(totalHeight));

        this.style()
                .set(ThemeProperties.BACKGROUND_COLOR, 0xFF151515) // Very dark background
                .set(ThemeProperties.BORDER_RADIUS, CornerRadii.all(4.0f))
                .set(ThemeProperties.BORDER_COLOR, 0xFF303030)
                .set(ThemeProperties.BORDER_THICKNESS, 1.0f);

        // Adjust content position inside panel with vertical offset fix.
        // We shift Y up by fontHeight to hide the empty line generated by createWrappingText logic.
        content.setX(Layout.pixel(padding));
        content.setY(Layout.pixel(padding - fontHeight));
        content.setWidth(Layout.pixel(contentWidth - (padding * 2)));

        this.add(content);

        // Original logic added 10px spacing after the panel for layout separation
        this.renderHeight = totalHeight + 10;
    }

    /**
     * Returns the pre-calculated height of this component including bottom margin.
     *
     * @return The total vertical space this component occupies.
     */
    public float getRenderHeight() {
        return renderHeight;
    }
}