/*
 * This file is part of XUI.
 * Licensed under MIT license.
 */
package net.xmx.xui.core.components.markdown;

import net.xmx.xui.core.Constraints;
import net.xmx.xui.core.components.UIPanel;
import net.xmx.xui.core.components.UIWrappedText;
import net.xmx.xui.core.font.UIFont;
import net.xmx.xui.core.style.Properties;
import net.xmx.xui.core.text.UITextComponent;

import java.util.List;

/**
 * Represents a Code Block in Markdown (```).
 * Renders text with syntax highlighting inside a dark box.
 *
 * @author xI-Mx-Ix
 */
public class MarkdownCodeBlock extends UIPanel {

    private final float renderHeight;

    /**
     * Constructs a code block component.
     *
     * @param lines        The lines of code.
     * @param contentWidth The available width.
     * @param font         The font to use for the code text.
     */
    public MarkdownCodeBlock(List<String> lines, float contentWidth, UIFont font) {
        StringBuilder sb = new StringBuilder();
        for (String s : lines) sb.append(s).append("\n");

        String code = sb.toString();
        // Retrieve the font height from the provided font instance
        float fontHeight = font.getLineHeight();

        // Apply syntax highlighting to the raw code string, returning a styled UITextComponent tree
        UITextComponent coloredCode = MarkdownUtils.highlightCode(code);
        
        // IMPORTANT: Recursively apply the code font to all highlight segments
        MarkdownUtils.applyFontRecursive(coloredCode, font);

        // Create wrapping text widget to handle line breaks
        UIWrappedText content = MarkdownUtils.createWrappingText(coloredCode, 0, contentWidth);

        float padding = 6;
        // Height Correction: Subtract empty line height caused by the wrapping text logic
        // The wrapping text widget adds an empty line at the start for padding layout,
        // so we subtract one line height to get the visual height.
        float totalHeight = (content.getHeight() - fontHeight) + (padding * 2);

        this.setWidth(Constraints.pixel(contentWidth));
        this.setHeight(Constraints.pixel(totalHeight));

        this.style()
                .set(Properties.BACKGROUND_COLOR, 0xFF151515) // Very dark background
                .set(Properties.BORDER_RADIUS, 4.0f)
                .set(Properties.BORDER_COLOR, 0xFF303030)
                .set(Properties.BORDER_THICKNESS, 1.0f);

        // Adjust content position inside panel with vertical offset fix.
        // We shift Y up by fontHeight to hide the empty line generated by createWrappingText.
        content.setX(Constraints.pixel(padding));
        content.setY(Constraints.pixel(padding - fontHeight));
        content.setWidth(Constraints.pixel(contentWidth - (padding * 2)));

        this.add(content);

        // Original logic added 10px spacing after the panel for layout separation
        this.renderHeight = totalHeight + 10;
    }

    /**
     * Returns the pre-calculated height of this component including bottom margin.
     *
     * @return The total vertical space this component occupies.
     */
    public float getRenderHeight() {
        return renderHeight;
    }
}